# From: https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release
name: Check for new release of SankeyMatic

# Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Download previous release info
        id: download-artifact
        uses: dawidd6/action-download-artifact@Latest # It's not possible to use actions/upload-artifact as of the time of writing
        with:
          name: sankeymatic-release-info
          workflow_conclusion: success
          workflow: publish.yml
          if_no_artifact_found: warn
          allow_forks: false

      - name: Get latest release
        id: get_release
        run: |
          # Fetch release information and extract the release tag
          LATEST_SHA=$(curl -s https://api.github.com/repos/nowthis/sankeymatic/commits/main | jq -r '.sha')
          echo "release_tag=$LATEST_SHA" >> $GITHUB_OUTPUT
          echo "latest release: $LATEST_SHA"

      - name: Compare with previous release
        id: compare_release
        run: |
          # Read the release info from the downloaded artifact
          PREVIOUS_SHA=$(cat sankeymatic-release-info 2> /dev/null || echo "NONE")
          echo "previous release: $PREVIOUS_SHA"

          # Compare the fetched release tag with the previous release tag
          if [ "${{ steps.get_release.outputs.LATEST_SHA }}" != "$PREVIOUS_SHA" ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
            echo "Release changed: true"
          else
            echo "release_changed=false" >> $GITHUB_OUTPUT
            echo "Release changed: false"
          fi

      - name: Call workflow to build code
        if: steps.compare_release.outputs.release_changed == 'true'
        uses: benc-uk/workflow-dispatch@Latest
        with:
          workflow: publish.yml
